backend:
  name: git-gateway
  branch: master

media_folder: "images"

collections:
  - name: "carousel"
    label: "Carousel"
    folder: "content/carousel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "img"}