backend:
  name: git-gateway
  branch: master

media_folder: "static/images"

collections:
  - name: "carousel"
    label: "Carousel"
    folder: "content/carousel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - label: "Home"
    name: "home"
    files:
      - label: "Home-Carousel"
        name: "carousel"
        file: "content/home/carousel.json"
        fields:
          - label: Carousel
            name: carousel
            widget: list
            fields:
              - {label: Title, name: title, widget: string }
              - {label: Description, name: description, widget: string }
              - {label: Image, name: image, widget: image }
      - label: "Features"
        name: "features"
        file: "content/home/features.json"
        fields:
          - label: Features
            name: features
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Icon,name: icon, widget: image}
      - label: "Projects"
        name: "projects"
        file: "content/home/projects.json"
        fields:
          - label: Projects
            name: projects
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Short Description, name: brief, widget: string}
              - {label: ProjectImage,name: projectImage, widget: image}
      - label: "Recommendations"
        name: "recommendations"
        file: "content/home/recommendations.json"
        fields:
          - label: Recommendations
            name: recommendations
            widget: list
            fields:
              - {label: RecommendedBy, name: recommendedby, widget: string}
              - {label: Profession, name: profession, widget: string}
              - {label: Recommendation,name: recommendation, widget: markdown}
              - {label: RecommendationProfileIcon,name: recommendationProfileIcon, widget: image}
      - label: "Steps of Installation"
        name: "steps"
        file: "content/home/steps-of-installation.json"
        fields:
          - label: 'Steps of Installation'
            name: stepsOfInstallation
            widget: list
            fields:
              - {label: Step Name, name: step, widget: string}