backend:
  name: git-gateway
  branch: master

media_folder: "static/images"

collections:
  - name: "carousel"
    label: "Carousel"
    folder: "content/carousel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - label: "Home"
    name: "home"
    files:
      - label: "Home-Carousel"
        name: "carousel"
        file: "content/home/carousel.json"
        fields:
          - label: Image
            name: team
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Features"
        name: "features"
        file: "content/home/features.json"
        fields:
          - label: Features
            name: feature
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Icon,name: icon, widget: image}
      - label: "Projects"
        name: "projects"
        file: "content/home/projects.json"
        fields:
          - label: Features
            name: feature
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown}
              - {label: ProjectImage,name: image, widget: image}